"""Added more columns to products

Revision ID: e7f4bd10155c
Revises: 
Create Date: 2025-03-13 17:11:23.428266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f4bd10155c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('products', 'price')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
